ContactWeb/ContactWeb/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContactWeb.Models;
using Microsoft.AspNet.Identity;

namespace ContactWeb.Controllers
{
    public class ContactsController : Controller
    {
        private ContactWebContext db = new ContactWebContext();

        // GET: Contacts
		[Authorize]
        public ActionResult Index()
        {
			var userId = GetCurrentUserId();
			return View(db.Contacts.Where(x => x.UserId == userId).ToList());
		}

		// GET: Contacts/Details/5
		[Authorize]
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null || !IsAuthorizedUser(contact))
            {
                return HttpNotFound();
            }
            return View(contact);
        }

		// GET: Contacts/Create
		[Authorize]
		public ActionResult Create()
        {
			ViewBag.UserId = GetCurrentUserId();
			return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize]
		public ActionResult Create([Bind(Include = "Id,UserId,FirstName,LastName,Email,birthday,contactPrim,contactSec,streetAddress1,streetAddress2,city,State,Zip")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
			ViewBag.UserId = GetCurrentUserId();
			return View(contact);
        }

		// GET: Contacts/Edit/5
		[Authorize]
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null || !IsAuthorizedUser(contact))
            {
                return HttpNotFound();
            }
			ViewBag.UserId = GetCurrentUserId();
			return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,FirstName,LastName,Email,birthday,contactPrim,contactSec,streetAddress1,streetAddress2,city,State,Zip")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
			ViewBag.UserId = GetCurrentUserId();
			return View(contact);
        }

		// GET: Contacts/Delete/5
		[Authorize]
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null || !IsAuthorizedUser(contact))
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Authorize]
		public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
			if(!IsAuthorizedUser(contact))
			{
				return HttpNotFound();
			}
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

		public Guid GetCurrentUserId()
		{
			return new Guid(User.Identity.GetUserId());
			/*try
			{
				var userId = new Guid(User.Identity.GetUserId());
				var userName = User.Identity.GetUserName();
				ViewBag.UserId = userId;
				ViewBag.UserName = userName;
				ViewData["UserId"] = userId;
				ViewData["UserName"] = userName;
			}
			catch (System.Exception ex)
			{

			}*/
		}

		private bool IsAuthorizedUser(Contact contact)
		{
			return contact.UserId == GetCurrentUserId();
		}

    }
}

ContactWeb/ContactWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contact Web Application</title>
    @Styles.Render("~/Content/css")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contact Web", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
					<li>@Html.ActionLink("Contact List", "Index","Contacts")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Contact Web Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/datatables")
	@Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>